name: CI/CD Pipeline

on:
  push:
    branches: [ main, blue, green ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build step (simulate)
        run: echo "Building the application..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests (simulate)
        run: echo "Running tests..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step (simulate)
        run: echo "Deploying application to production..."
